apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: radufirst/hello-world-node:latest
    ports:
    - containerPort: 3000
  

